# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from .W_pb2 import ServerRequest
from .W_pb2 import ServerResponse


class gRPCStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetMessage = channel.unary_unary(
        '/gRPC/GetMessage',
        request_serializer=ServerRequest.SerializeToString,
        response_deserializer=ServerResponse.FromString,
        )


class gRPCServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def GetMessage(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_gRPCServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetMessage': grpc.unary_unary_rpc_method_handler(
          servicer.GetMessage,
          request_deserializer=ServerRequest.FromString,
          response_serializer=ServerResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'gRPC', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
